// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrGyW4aCUoZgbrFir51cIuzSQXrrlVmq4',
    appId: '1:661889907814:web:4619df6973bcc4bb3101a7',
    messagingSenderId: '661889907814',
    projectId: 'app-explorer-city',
    authDomain: 'app-explorer-city.firebaseapp.com',
    storageBucket: 'app-explorer-city.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkxZJ1TiEqCisiEpHULHpni_TDv7iBkgo',
    appId: '1:661889907814:android:3310197d4db269883101a7',
    messagingSenderId: '661889907814',
    projectId: 'app-explorer-city',
    storageBucket: 'app-explorer-city.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD36dwaC76-JekVHu8CWAQjIM96ooNLzGQ',
    appId: '1:661889907814:ios:7c08b38ede9660653101a7',
    messagingSenderId: '661889907814',
    projectId: 'app-explorer-city',
    storageBucket: 'app-explorer-city.firebasestorage.app',
    iosBundleId: 'com.example.explorerCityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD36dwaC76-JekVHu8CWAQjIM96ooNLzGQ',
    appId: '1:661889907814:ios:7c08b38ede9660653101a7',
    messagingSenderId: '661889907814',
    projectId: 'app-explorer-city',
    storageBucket: 'app-explorer-city.firebasestorage.app',
    iosBundleId: 'com.example.explorerCityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrGyW4aCUoZgbrFir51cIuzSQXrrlVmq4',
    appId: '1:661889907814:web:57bad63ad4becf4a3101a7',
    messagingSenderId: '661889907814',
    projectId: 'app-explorer-city',
    authDomain: 'app-explorer-city.firebaseapp.com',
    storageBucket: 'app-explorer-city.firebasestorage.app',
  );
}
